### ISSUE TITLE
Modcraft could help?

### ISSUE THREAD

**Issue by Helias** [stoneharry/WoW-Custom-Class#1]
This guy probably already did it, I think that you already see it, so what's wrong with this tutorial? the guide is outdated?

If you didn't already see this, take a look here: http://www.modcraft.io/index.php?topic=3838.0

**Comment by stoneharry** [comment]
It doesn't include everything necessary, only the shell. My guide does not include much more at the moment, but when I return to this project I will giving much more detail. Also I am automating any big tasks so that it is easy to modify and change. Making many custom classes should be easy with the spell editor and anything produced from this project.

The eventual goal is to integrate the code produced in this project into the spell editor so you can create/modify/delete classes from there.

**Comment by Helias** [comment]
Ok, I really appreciate this, so thanks for your work, know that I'm following you and this repo :wink:
